# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a22985cb8cbe29f65d3cb3bbb623c03735928bf6c77a5f92f90ef3d27a6cd0343611ea64e804f84ec49cbea97a3ae01c26cd90ac402384925d51550ce70a7cf

test:
  secret_key_base: c87e381c4d0748573ed973a62f7685d867ce79b5429a559076de3594a43e64e2e6312f69eabe6dfc06fd5568e244cc3c2754321acf4108fd1c99fc71aec87a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
